### ISSUE TITLE
How to re-enable the disabled one?

### ISSUE THREAD

**Issue by ejamshidiasl** [romanvolodin/dynamic_parent#5]
Hello and thanks for really good addon.
i need to re-enable the disabled constraint. is it possible to do that? how?

**Comment by romanvolodin** [comment]
You're very welcome! =)

No, unfortunately it’s not possible. When you disable DP, Blender calculates constraint transform matrix for the child object. Since a constraint can have only one matrix, we have to create new constraint each time.
