### ISSUE TITLE
QOL Suggestion: When attempting to parent armature to child in Object mode, show user a warning with the solution

### ISSUE THREAD

**Issue by HeyItsLollie** [romanvolodin/dynamic_parent#9]
I was in Object Mode, and attempted to parent an armature to an empty. This threw the error below:

```Python: Traceback (most recent call last):
  File "C:\Users\Zenuel\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dynamic_parent.py", line 251, in execute
    const = get_last_dymanic_parent_constraint(obj)
  File "C:\Users\Zenuel\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dynamic_parent.py", line 58, in get_last_dymanic_parent_constraint
    if not obj.constraints:
AttributeError: 'NoneType' object has no attribute 'constraints'
```

I was able to find the solution via #4: Create the dynamic parent for the armature in Pose Mode instead of Object Mode.

The issue is that the plug-in should catch this, and throw a warning with solution - for example, like how it warns the user when only a single object is selected:
![blender - 2022-12-08 - 13-15-42](https://user-images.githubusercontent.com/30498581/206347379-c70068cf-fa6f-483d-8293-e1d0814226d9.png)

**Comment by romanvolodin** [comment]
Reopened the issue in case you have something to add.

**Comment by HeyItsLollie** [comment]
Nothing else to add, thank you for adding it so quickly!
